name: Notify Homebrew Tap

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Homebrew repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/thewebAI/homebrew-webai/dispatches \
            -d '{"event_type": "new_release", "client_payload": {"version": "${{
            github.event.release.tag_name }}"}}'
            -v
